### ISSUE TITLE
getMoments returns wrong number of rows

### ISSUE THREAD

**Issue by BayerSe** [LeopoldoCatania/GAS#2]
Hi,

in the current CRAN version of this package (0.2.9), I observed the problem that the number of conditional moments does not match the length of the return series for a simulated GAS process. Same problem with `getFilteredParameters`, `quantile`,  and `ES`.

Steps to reproduce this problem:
```
r <- rnorm(1000)
spec <- GAS::UniGASSpec()
fit <- GAS::UniGASFit(spec, r)
sim <- GAS::UniGASSim(fit = fit, T.sim = 1000)
r_sim <- getObs(sim)
moments_sim <- getMoments(sim)
stopifnot(length(r_sim) == nrow(moments_sim))
```

**Comment by LeopoldoCatania** [comment]
Hi, UniGASSim() simulates T.sim observations.

getMoments returns also the one step ahead prediction which is at position T.sim + 1.
