### ISSUE TITLE
package ‘truncnorm’ is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by AlexSemenovIRL** [LeopoldoCatania/GAS#3]
Can't load the library under R version 3.3.3 as the package `truncnorm` is required which only supports R 3.4 and above. 

`library(GAS)

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘truncnorm’
Error: package or namespace load failed for ‘GAS’

install.packages("truncnorm")

Warning in install.packages :
  package ‘truncnorm’ is not available (for R version 3.3.3)`

As per docs below it was built using 3.3.3, can you have a look please

> Package: GAS
Type: Package
Title: Generalized Autoregressive Score Models
Version: 0.2.6
Author: Leopoldo Catania [aut,cre], Kris Boudt [ctb], David Ardia [ctb]
Maintainer: Leopoldo Catania <leopoldo.catania@econ.au.dk>
Description: Simulate, estimate and forecast using univariate and multivariate GAS models 
  as described in Ardia et al. (2016) <https://ssrn.com/abstract=2825380>.
License: GPL-3
BugReports: https://github.com/LeopoldoCatania/GAS/issues
URL: https://github.com/LeopoldoCatania/GAS
LazyData: TRUE
Imports: Rcpp (>= 0.12.2), Rsolnp, MASS, xts, numDeriv, zoo
LinkingTo: Rcpp, RcppArmadillo
Depends: R (>= 3.2.0), methods
Suggests: testthat
NeedsCompilation: yes
Packaged: 2017-12-19 12:12:24 UTC; leopo
Repository: CRAN
Date/Publication: 2017-12-20 13:42:07 UTC
Built: R 3.3.3; x86_64-w64-mingw32; 2018-04-22 15:40:02 UTC; windows
Archs: i386, x64

**Comment by ArdiaD** [comment]
From Alex again:
I think the R version should be stated to be 3.4 and above as package truncnorm is required which doesn't work with 3.3.3 ( odd because on CRAN you built it using Built: R 3.3.3, as per the docs)
