### ISSUE TITLE
Can extract residuals from univariate GAS model

### ISSUE THREAD

**Issue by sminloo** [LeopoldoCatania/GAS#4]
I cannot extract the residuals 

gas_spec <- UniGASSpec(Dist = "std", ScalingType = "Inv", 
                      GASPar = list(location = TRUE, scale = TRUE, shape = FALSE))
gas_sp_fit <-UniGASFit(gas_spec,dji30ret[1:1000,"GE"])
> residuals(gas_sp_fit)
Error: $ operator not defined for this S4 class
> residuals(gas_sp_roll)
Error: $ operator not defined for this S4 class

**Comment by LeopoldoCatania** [comment]
Dear Shi,

you have probably loaded another package that defines the residual method after GAS (like rugarch). Try to run 

GAS:: residuals(gas_sp_fit)

Best,
Leopoldo

**Comment by sminloo** [comment]
Dear dr.Catania,

Thank you so much!
You are my hero!

Best,
Minglong Shi


On 4 Apr 2019, at 9:35 AM, Leopoldo Catania <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Shi,

you have probably loaded another package that defines the residual method after GAS (like rugarch). Try to run

GAS:: residuals(gas_sp_fit)

Best,
Leopoldo
