### ISSUE TITLE
Addition of Generalised Lambda Distribution (GLD)

### ISSUE THREAD

**Issue by bethpeniel** [LeopoldoCatania/GAS#6]
Hello Catania,

I would suggest to you to add the Generalised Lambda Distribution (GLD) and its various forms to the number of distributions implemented in the GAS package.

I hope to see this in the near future.

Thank you.

**Comment by ArdiaD** [comment]
Hi @bethpeniel plz PR and we will add

**Comment by bethpeniel** [comment]
Hi Leopoldo,
Great. I understand you have added the GLD.
I do not understand the other part of the message.

**Comment by bethpeniel** [comment]
Kindly add me. Thanks.

**Comment by ArdiaD** [comment]
1) @ArdiaD replied, not @LeopoldoCatania 
2) We do not intend to add the distribution. Code it yourself and then make a pull request. We will add it.

**Comment by bethpeniel** [comment]
Noted. Thanks.
