### ISSUE TITLE
GAS 0.3.0 removed from CRAN on 2020-02-24

### ISSUE THREAD

**Issue by Fifis** [LeopoldoCatania/GAS#8]
This package is no longer available, but it contains incredibly useful functions (such as Engle—Manganelli’s DQ test). One has to resort to `install_version` from `devtools`.
Is there any chance to see it online again after the problems with the package mentioned by CRAN are addressed?

**Comment by ArdiaD** [comment]
We fixed the problem; package should be on CRAN in 1-2 days once @LeopoldoCatania has resubmitted
